theme: minima
author: Anna Kinder
email: annamkinder@yahoo.com
phone: 314-605-1640

# social links
github_username:  annamkinder

show_excerpts: true # set to false to remove excerpts on the homepage
